"""create properties table

Revision ID: 34f176adbbbf
Revises: 
Create Date: 2026-08-13 07:15:30.130194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f176adbbbf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('purpose', sa.String(length=10), nullable=False),
    sa.Column('property_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.Column('locality', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('furnished', sa.Boolean(), nullable=False),
    sa.Column('availability', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("property_type IN ('house', 'studio', 'commercial')", name='ck_properties_property_type'),
    sa.CheckConstraint("purpose IN ('buy', 'rent')", name='ck_properties_purpose'),
    sa.CheckConstraint("status IN ('draft', 'published', 'sold', 'rented', 'archived')", name='ck_properties_status'),
    sa.CheckConstraint('area > 0', name='ck_properties_positive_area'),
    sa.CheckConstraint('price > 0', name='ck_properties_positive_price'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_featured'), 'properties', ['featured'], unique=False)
    op.create_index(op.f('ix_properties_locality'), 'properties', ['locality'], unique=False)
    op.create_index(op.f('ix_properties_price'), 'properties', ['price'], unique=False)
    op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)
    op.create_index(op.f('ix_properties_purpose'), 'properties', ['purpose'], unique=False)
    op.create_index(op.f('ix_properties_slug'), 'properties', ['slug'], unique=True)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_slug'), table_name='properties')
    op.drop_index(op.f('ix_properties_purpose'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_price'), table_name='properties')
    op.drop_index(op.f('ix_properties_locality'), table_name='properties')
    op.drop_index(op.f('ix_properties_featured'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
