"""add saves contacts owner submissions

Revision ID: 443e3b446be8
Revises: bdd4a9e16274
Create Date: 2026-08-15 03:00:44.163012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '443e3b446be8'
down_revision: Union[str, Sequence[str], None] = 'bdd4a9e16274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=60), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'reviewed', 'closed', 'spam')", name='ck_contact_messages_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_created_at'), 'contact_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_contact_messages_email'), 'contact_messages', ['email'], unique=False)
    op.create_index(op.f('ix_contact_messages_status'), 'contact_messages', ['status'], unique=False)
    op.create_index(op.f('ix_contact_messages_subject'), 'contact_messages', ['subject'], unique=False)
    op.create_table('owner_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('purpose', sa.String(length=10), nullable=False),
    sa.Column('property_type', sa.String(length=20), nullable=False),
    sa.Column('locality', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('expected_price', sa.BigInteger(), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('furnishing', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('authority_confirmed', sa.Boolean(), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("property_type IN ('house', 'studio', 'commercial')", name='ck_owner_submissions_property_type'),
    sa.CheckConstraint("purpose IN ('sell', 'rent')", name='ck_owner_submissions_purpose'),
    sa.CheckConstraint("status IN ('new', 'reviewing', 'approved', 'rejected')", name='ck_owner_submissions_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_submissions_created_at'), 'owner_submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_owner_submissions_email'), 'owner_submissions', ['email'], unique=False)
    op.create_index(op.f('ix_owner_submissions_locality'), 'owner_submissions', ['locality'], unique=False)
    op.create_index(op.f('ix_owner_submissions_status'), 'owner_submissions', ['status'], unique=False)
    op.create_table('saved_properties',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'property_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_properties')
    op.drop_index(op.f('ix_owner_submissions_status'), table_name='owner_submissions')
    op.drop_index(op.f('ix_owner_submissions_locality'), table_name='owner_submissions')
    op.drop_index(op.f('ix_owner_submissions_email'), table_name='owner_submissions')
    op.drop_index(op.f('ix_owner_submissions_created_at'), table_name='owner_submissions')
    op.drop_table('owner_submissions')
    op.drop_index(op.f('ix_contact_messages_subject'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_status'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_email'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_created_at'), table_name='contact_messages')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
